failure-threshold: warning # name of threshold level (error | warning | info | style | ignore | none)
format: checkstyle # Output format (tty | json | checkstyle | codeclimate | gitlab_codeclimate | codacy)
# ignored: [string] # list of rules
# label-schema: # See Linting Labels below for specific label-schema details
#   author: string # Your name
#   contact: string # email address
#   created: timestamp # rfc3339 datetime
#   version: string # semver
#   documentation: string # url
#   git-revision: string # hash
#   license: string # spdx
no-color: false # true | false
no-fail: false # true | false
# override:
#   error: [string] # list of rules
#   warning: [string] # list of rules
#   info: [string] # list of rules
#   style: [string] # list of rules
strict-labels: false # true | false
trustedRegistries: docker.io | ghcr.io # registry or list of registries
