# See. https://github.com/yoheimuta/protolint#rules
# Samples. https://github.com/yoheimuta/protolint/blob/master/_example/config/.protolint.yaml
lint:
  rules:
    all_default: true
    remove:
      - MESSAGES_HAVE_COMMENT
      - SERVICES_HAVE_COMMENT
      - RPCS_HAVE_COMMENT
      - FIELDS_HAVE_COMMENT
      - ENUMS_HAVE_COMMENT
      - ENUM_FIELDS_HAVE_COMMENT
