name: build generator image

on:
  tags:
    - "v*.*.*"
  pull_request:

jobs:
  build:
    uses: mintak21/actions/.github/workflows/build_ghcr.yml@455fd8166bf2cccda3735890a4026cfc9e1c1bed
    with:
      image: ${{ github.repository }}/builder
