name: build generator image

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1
  IMAGE_CACHE_DIR: tmp/docker/cache

jobs:
  build:
    name: build generator image
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2

      - name: Get Version
        id: version
        run: |
          echo ::set-output name=source_branch::${GITHUB_REF#refs/heads/}
          echo ::set-output name=source_tag::${GITHUB_REF#refs/tags/}
      # kaniko actionはgchrに未対応、docker.pkg.github.comならば使用できる
      # - name: kaniko build
      #   uses: aevea/action-kaniko@v0.6.1
      #   with:
      #     registry: docker.pkg.github.com
      #     build_file: Dockerfile
      #     username: mintak21
      #     password: ${{ secrets.GHCR_ACCESS_TOKEN }}
      #     image: proto-builder
      #     tag: latest
      #     cache: true
      #     cache_registry: proto-builder-cache

      - name: Build and Push to GitHub Container Registry
        id: push-ghcr
        env:
          DOCKER_FILE: Dockerfile
          IMAGE_TAG: latest
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}
          repository: ${{ github.repository }}-builder
          dockerfile: ${{ env.DOCKER_FILE }}
          tags: ${{ env.IMAGE_TAG }}
