name: build generator image

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: build generator image
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2

      - name: Get Version
        id: version
        run: |
          echo "source_branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "source_tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: builder
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.2

      - name: Login to Github Container Registry
        id: login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}

      # reference. https://github.com/docker/build-push-action/issues/99#issuecomment-685703519
      - name: Build and Push Image
        id: build-push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder.outputs.name }}
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}-builder:v2test # ghcr.io/ 部分は必要、ただしghcr.io/{username}のusername部分はイメージ名扱いになる
      # v1 のやり方、古い
      # - name: Build and Push to GitHub Container Registry
      #   id: push-ghcr
      #   env:
      #     DOCKER_FILE: Dockerfile
      #     IMAGE_TAG: latest
      #   uses: docker/build-push-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GHCR_ACCESS_TOKEN }}
      #     repository: ${{ github.repository }}-builder
      #     dockerfile: ${{ env.DOCKER_FILE }}
      #     tags: ${{ env.IMAGE_TAG }}
      #############
      # kaniko actionはgchrに未対応と思われる、docker.pkg.github.comならば使用できる
      # - name: kaniko build
      #   uses: aevea/action-kaniko@v0.6.1
      #   with:
      #     registry: docker.pkg.github.com
      #     build_file: Dockerfile
      #     username: mintak21
      #     password: ${{ secrets.GHCR_ACCESS_TOKEN }}
      #     image: proto-builder
      #     tag: latest
      #     cache: true
      #     cache_registry: proto-builder-cache
