name: ci

on:
  push:
    branches:
      - main

jobs:
  dockerfile-lint:
    name: dockerfile lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2

      - name: Check Dockerfile
        id: lint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          config: ./.hadolint.yaml

      - name: Login to Github Container Registry
        id: login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Build and Push Image
        id: build-push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ github.repository }}-builder:v2test
      # v1 のやり方、古い
      # - name: Build and Push to GitHub Container Registry
      #   id: push-ghcr
      #   env:
      #     DOCKER_FILE: Dockerfile
      #     IMAGE_TAG: latest
      #   uses: docker/build-push-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GHCR_ACCESS_TOKEN }}
      #     repository: ${{ github.repository }}-builder
      #     dockerfile: ${{ env.DOCKER_FILE }}
      #     tags: ${{ env.IMAGE_TAG }}
      #############
      # kaniko actionはgchrに未対応と思われる、docker.pkg.github.comならば使用できる
      # - name: kaniko build
      #   uses: aevea/action-kaniko@v0.6.1
      #   with:
      #     registry: docker.pkg.github.com
      #     build_file: Dockerfile
      #     username: mintak21
      #     password: ${{ secrets.GHCR_ACCESS_TOKEN }}
      #     image: proto-builder
      #     tag: latest
      #     cache: true
      #     cache_registry: proto-builder-cache
