name: ci

on:
  push:
    branches:
      - main

jobs:
  dockerfile-lint:
    name: dockerfile lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2

      - name: Check Dockerfile
        id: lint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          config: ./.hadolint.yaml
